md_extensions:
  - 'rdm.md_extensions.SectionNumberExtension'
  - 'rdm.md_extensions.VocabularyExtension'
    #- 'rdm.md_extensions.AuditNoteExclusionExtension'

# The repository location within the project management tool
repository: user/repository

project_management_backend: 'rdm.project_management.GitHubIssueBackend'

reviews_required: True
